### ISSUE TITLE
文档中能加一下如何使用的详细教程吗

### ISSUE THREAD

**Issue by colinshin** [PinkHello/go-starter#2]
文档中能加一下如何使用的详细教程吗

**Comment by pinkhello** [comment]
稍等，今天我抽空加一下

**Comment by pinkhello** [comment]
> 文档中能加一下如何使用的详细教程吗

我今天加一下

**Comment by pinkhello** [comment]
> 文档中能加一下如何使用的详细教程吗

https://github.com/pinkhello/go-starter/blob/main/Guide.md
